## run "brew bundle"
# taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "wata727/tflint"
tap "hashicorp/tap"

# casks
# cask "1password"
# cask "docker"
# cask "dropbox"
# cask "evernote"
# cask "iterm22"
cask "muzzle"

# brews
brew "autojump"
brew "dep"
brew "direnv"
brew "fontconfig"
brew "fzf"
brew "git"
brew "glide"
brew "ipcalc"
brew "jq"
brew "nmap"
brew "mtr"
brew "speedtest-cli"
brew "sshuttle"
brew "stern"
brew "tflint"
brew "watch"
brew "wget"
brew "k9s"
brew "telnet"
brew "grepcidr"
brew "packer"
brew "esolitos/ipa/sshpass"
brew "virtualenv"
brew "vault"
brew "iterm2"
brew "iproute2mac"